# Generated by Django 4.2.4 on 2023-08-24 08:23

from django.db import migrations


def forwards(apps, schema_editor):
    Contact = apps.get_model("app", "Contact")
    PhoneNumber = apps.get_model("app", "PhoneNumber")
    alice = Contact.objects.create(first_name="Alice", last_name="Demoman")
    PhoneNumber.objects.create(contact=alice, label="Home", number="12345678")
    PhoneNumber.objects.create(contact=alice, label="Work", number="87654321")


def reverse(apps, schema_editor):
    Contact = apps.get_model("app", "Contact")
    PhoneNumber = apps.get_model("app", "PhoneNumber")
    Contact.objects.all().delete()
    PhoneNumber.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards, reverse)]
